### ISSUE TITLE
Invalid regular expression in Bad words filter throwing PHP warning

### ISSUE THREAD

**Issue by AndreRl** [mybb/mybb#3354]
Bad words filter is not working in 1.8.17 for `*jeb*` and `*јеб*` on https://www.medicinari.com/forum at all.

When that is checked as Regular Expression I am getting on front end of forum next:

Quote:
Warning [2] preg_replace() [function.preg-replace]: Compilation failed: nothing to repeat at offset 0 - Line: 655 - File: inc/class_parser.php PHP 5.3.29 (Linux)
File
Line
Function[PHP]
 
errorHandler->error
/inc/class_parser.php
655
preg_replace
/inc/functions_post.php
169
postParser->parse_badwords
/showthread.php
1110
build_postbit
Warning [2] preg_replace() [function.preg-replace]: Compilation failed: nothing to repeat at offset 0 - Line: 655 - File: inc/class_parser.php PHP 5.3.29 (Linux)
File
Line
Function[PHP]
 
errorHandler->error
/inc/class_parser.php
655
preg_replace
/inc/class_parser.php
134
postParser->parse_badwords
/inc/functions_post.php
774
postParser->parse_message
/showthread.php
1110
build_postbit
Warning [2] preg_replace() [function.preg-replace]: Compilation failed: nothing to repeat at offset 0 - Line: 655 - File: inc/class_parser.php PHP 5.3.29 (Linux)
File
Line
Function[PHP]
 
errorHandler->error
/inc/class_parser.php
655
preg_replace
/inc/class_parser.php
134
postParser->parse_badwords
/inc/functions_post.php
774
postParser->parse_message
/showthread.php
1110
build_postbit
Line
Function[PHP]
 
errorHandler->error
/inc/class_parser.php
655
preg_replace
/inc/functions_post.php
169
postParser->parse_badwords
/showthread.php
1110
build_postbit

Regards,
Serbian Translator

Original thread: [Bad words filter is not working in 1.8.17](https://community.mybb.com/thread-218804.html)
